### ISSUE TITLE
Add support for _bulk_docs

### ISSUE THREAD

**Issue by akheron** [inoi/trombi#4]
couchdb-python has a nice API for bulk document updates. I'd like to see a similar API in trombi.

**Comment by nailor** [comment]
Database API: Implement bulk_docs support.

This implements support for modification of CouchDB documents through
_bulk_docs API entry point. It introduces new result types:
BulkResult, BulkError and BulkObject.

Closed by 9865ae7678a0c4c4b5e8734bd866528b70d42566.
